# Site settings
title: Mayukh's blog
description: 
baseurl: 
relative_url: True
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mayukh Deb
user_description: Mario jumps over luigi. 
user_title: Making computers see things
email: mayukhmainak2000@gmail.com
twitter_username: mayukh091
github_username:  mayukhdeb

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
